default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    cocoapods
    run_tests(scheme: "FastBike")
    increment_version_number(version_number: '1.2')
    next_build_number = 1 + latest_testflight_build_number(version: "1.2")
    increment_build_number(build_number: next_build_number)
    build_app(scheme: "FastBike",
      force: true,
      configuration: "Release",
      export_options: {
      method: "app-store",
    })
    upload_to_app_store
  end
end
